# Generated by Django 4.1.7 on 2023-08-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scrap'),
        ('main', '0004_review_user'),
    ]

    operations = [
    ]
