# Generated by Django 4.2.4 on 2023-08-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='date_scraped',
        ),
    ]
