# Generated by Django 4.1.7 on 2023-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_scrap_date_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='wordcloud_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
