# Generated by Django 4.2.4 on 2023-08-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_store_image_store_operation_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_image',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.store'),
        ),
    ]
