# Generated by Django 4.1.7 on 2023-08-15 15:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_chat_wordcloud_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path),
        ),
    ]
