# Generated by Django 4.2.4 on 2023-08-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_store_image_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='road_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_other_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
