# Generated by Django 4.1.7 on 2023-08-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_store_rating_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
