# Generated by Django 4.1.7 on 2023-08-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_store_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rating',
        ),
    ]
