# Generated by Django 4.1.7 on 2023-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_store_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='wordcloud_image',
            field=models.ImageField(default=None, upload_to='chat'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wordclouds/'),
        ),
    ]
