# Generated by Django 4.2.4 on 2023-08-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_store_road_address_and_more'),
        ('main', '0013_remove_store_rating'),
    ]

    operations = [
    ]
