# Generated by Django 4.1.7 on 2023-08-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_chat_wordcloud_image_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='wordcloud_image',
            field=models.ImageField(blank=True, null=True, upload_to='wordclouds/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviewimage/'),
        ),
    ]
