# Generated by Django 4.2.4 on 2023-08-15 19:48

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_merge_20230815_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AlterField(
            model_name='store_image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.store_image_upload_path),
        ),
    ]
