# Generated by Django 4.2.4 on 2023-08-15 19:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_review_image_alter_store_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='wordcloud_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path),
        ),
    ]
