# Generated by Django 4.1.7 on 2023-08-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_chat_wordcloud_image_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='wordcloud_image',
            field=models.ImageField(default='default_wordcloud.png', upload_to='chat/'),
        ),
    ]
