# Generated by Django 4.2.4 on 2023-08-15 19:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_chat_wordcloud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='wordcloud_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.store_image_upload_path),
        ),
    ]
