# Generated by Django 4.1.7 on 2023-08-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_chat_wordcloud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='wordcloud_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
    ]
