# Generated by Django 4.2.4 on 2023-08-15 20:02

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_chat_wordcloud_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.image_upload_path)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.review')),
            ],
        ),
    ]
