# Generated by Django 4.2.4 on 2023-08-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_menu_name_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
